import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
const base='http://127.0.0.1:3211';const root=path.resolve('test-output','multi-v104-'+Date.now());fs.mkdirSync(root,{recursive:true});
const post=async(p,b)=>{const r=await fetch(base+p,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});const d=await r.json();if(!d.ok)throw Error(JSON.stringify(d));return d};
const ws=await post('/api/workspaces',{path:root});
const settings={provider:{baseUrl:'http://127.0.0.1:1234/v1',model:'qwen/qwen3.5-9b',autoModelLimits:true,temperature:0.2},agent:{maxIterations:0,stageMaxIterations:0},contextTools:{skills:false},autoPrompt:{enabled:true,stages:['review','completeness']}};
const created=await post('/api/runs',{clientRequestId:crypto.randomUUID(),sessionId:'multi_'+Date.now(),workspaceId:ws.workspace.id,mode:'code',task:'Build a small CommonJS statistics module in src/stats.cjs exporting mean(numbers) and median(numbers), both returning null for an empty array. Write stats.test.cjs with node:assert/strict covering mean, median for odd/even counts, negatives and empty input. Create package.json with npm test running that test file. Implement the functions and tests, run npm test, then call attempt_completion with the evidence.',settings});
const response=await fetch(base+'/api/runs/'+created.runId+'/events');const dec=new TextDecoder();let buf='';const events=[];
for await(const c of response.body){buf+=dec.decode(c,{stream:true});const lines=buf.split('\n');buf=lines.pop()||'';for(const l of lines){if(!l.startsWith('data:'))continue;const e=JSON.parse(l.slice(5));events.push(e);if(['tool.finished','stage.started','stage.finished','run.finished','error'].includes(e.type))console.log(e.type,JSON.stringify(e.data).slice(0,450));}}
const {run}=await fetch(base+'/api/runs/'+created.runId).then(r=>r.json());fs.writeFileSync(path.join(root,'evidence.json'),JSON.stringify({run,events},null,2));assert.equal(run.state,'succeeded');assert.deepEqual(events.filter(e=>e.type==='stage.started').map(e=>e.data.stage),['review','completeness']);assert.ok(events.filter(e=>e.type==='stage.finished').every(e=>e.data.passed));console.log('MULTIFILE_PIPELINE_PASS',root);
